name: 🐛 不具合報告
description: 不具合だと感じた方はこちら
labels: ["⚠️不具合審査中"]

body:
  - type: markdown
    attributes:
      value: |
        ご報告いただきありがとうございます！
        報告の前に同様の事象が本リポジトリまたは、フォーム元の misskey-dev/misskey で投稿されていないがご確認ください。
        もしOtaku Socialが運営するMisskeyサーバー以外で発生している事象の場合は、本フォームではなく在籍中のサーバー管理者までご連絡ください。（本フォームはOtaku Socialが管理するMisskeyサーバーのブランチのため、他サーバーの事象については対応できません。）

  - type: textarea
    attributes:
      label: 💡 概要
      description: どういった不具合なのかを教えてください。
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🥰 期待する動作
      description: どういった動作が正しいものかをご記載ください。
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🤬 現在の動作
      description: |
        現在の動作についてご記載下さい。
        もし画面にエラーが表示された場合は、合わせてご記入ください。
    validations:
      required: true

  - type: textarea
    attributes:
      label: 📝 再現手順
      placeholder: |
        事象発生までの再現手順をできるだけ具体的にご記載ください。
        1.
        2.
        3.
    validations:
      required: false

  - type: textarea
    attributes:
      label: 💻 利用環境
      description: |
        不具合が発生した環境を記載してください。

        例:
          * OSや端末名: Windows 11 64bit (23H2)
          * ご利用のブラウザ: Google Chrome 121.0.6167.185（Official Build） （64 ビット）
      value: |
        * OSや端末名:
        * ご利用のブラウザ:
      render: markdown
    validations:
      required: false
