name: ✨ 提案
description: 本プロジェクトへの提案
labels: ["✨提案"]

body:
  - type: textarea
    attributes:
      label: 概要
      description: どのようなことを提案したいのか教えてください。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 目的
      description: どういった目的なのか教えてください。
    validations:
      required: true
